// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActionController from "./action_controller"
application.register("action", ActionController)

import DispoController from "./dispo_controller"
application.register("dispo", DispoController)

import Select2Controller from "./select2_controller"
application.register("select2", Select2Controller)

// https://github.com/rbague/stimulus-check-all

import CheckAll from "stimulus-check-all"
application.register("check-all", CheckAll)